<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Contains wxt_ext_editor.module.
 */

/**
 * Implements hook_editor_js_settings_alter().
 */
function wxt_ext_editor_editor_js_settings_alter(array &$settings) {
  foreach ($settings['editor']['formats'] as &$format) {
    // Add a small ckeditor faux plugin.
    if (isset($format['editor']) && $format['editor'] == 'ckeditor') {
      $format['editorSettings']['drupalExternalPlugins']['wxt_ext_editor'] = base_path() . \Drupal::service('extension.list.module')->getPath('wxt_ext_editor') . '/js/wxt_ext_editor.js';
      $format['editorSettings']['extraPlugins'] .= ',wxt_ext_editor';
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function wxt_ext_editor_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $moduleHandler = \Drupal::service('module_handler');

  // Add ckeditor5 library to forms that use ckeditor5.
  if ($moduleHandler->moduleExists('ckeditor5')) {
    foreach ($form as $key => $value) {
      if (!is_object($value)) {
        if (!empty($value['widget'][0]['#type']) && $value['widget'][0]['#type'] == 'text_format') {
          $form['#attached']['library'][] = 'wxt_ext_editor/ckeditor5';
          break;
        }
      }
    }
  }
}
