<?php

/**
 * @file
 * Contains wxt_ext_editor.module.
 */

/**
 * Implements hook_editor_js_settings_alter().
 */
function wxt_ext_editor_editor_js_settings_alter(array &$settings) {
  foreach ($settings['editor']['formats'] as &$format) {
    // Add a small ckeditor faux plugin.
    if (isset($format['editor']) && $format['editor'] == 'ckeditor') {
      $format['editorSettings']['drupalExternalPlugins']['wxt_ext_editor'] = base_path() . \Drupal::service('extension.list.module')->getPath('wxt_ext_editor') . '/js/wxt_ext_editor.js';
      $format['editorSettings']['extraPlugins'] .= ',wxt_ext_editor';
    }
  }
}

/**
 * Implements hook_preprocess_form_element().
 */
function wxt_ext_editor_preprocess_form_element(array &$variables) {
  $element = $variables['element'];
  $moduleHandler = \Drupal::service('module_handler');

  // Add ckeditor5 library to forms that use ckeditor5.
  if ($moduleHandler->moduleExists('ckeditor5')) {
    // Check if the element has a text format.
    if (isset($element['#type']) && $element['#type'] === 'textarea' && isset($element['#format'])) {
      // Attach CSS library to the form.
      $variables['#attached']['library'][] = 'wxt_ext_editor/ckeditor5';
    }
  }
}
