<?php

/**
 * @file
 * Support for file media assets in WxT Extend Image.
 */

use Drupal\wxt_core\OverrideHelper as Override;
use Drupal\wxt_ext_media_document\Plugin\media\Source\File;

/**
 * Implements hook_media_source_info_alter().
 */
function wxt_ext_media_document_media_source_info_alter(array &$sources) {
  $sources['file']['input_match']['field_types'] = ['file'];
  Override::pluginClass($sources['file'], File::class);
}
