<?php

/**
 * @file
 * Set up the WxT Extend Landing Page module.
 */

/**
 * Implements hook_install().
 */
function wxt_ext_landing_page_install() {
  // Stop here during a config sync.
  if (Drupal::isConfigSyncing()) {
    return;
  }

  // Enable translation for our core entities/bundles.
  $entities = [
    'node' => [
      'landing_page',
    ],
  ];
  wxt_translation_enable_translation($entities);
}
