<?php

/**
 * @file
 * Contains wxt_ext_page.install.
 */

/**
 * Implements hook_install().
 */
function wxt_ext_page_install() {
  // Enable translation for our core entities/bundles.
  $entities = [
    'node' => [
      'page',
    ],
  ];
  wxt_translation_enable_translation($entities);

  // Download the newest config translations from Drupal.org.
  wxt_translation_update_config_translation();
}
