user.role.*.third_party.wxt:
  type: mapping
  label: 'WxT settings'
  mapping:
    bundled:
      type: boolean
      label: 'Bundled with WxT'

wxt.versions:
  type: config_object
  label: 'WxT component versions'
  mapping:
    config_value:
      type: string
      label: 'Version'
