<?php

/**
 * @file
 * Contains wxt_ext_media.module.
 *
 * Leveraged from code provided by Acquia for the Lightning distribution.
 */

/**
 * Implements hook_install().
 */
function wxt_ext_media_install() {
  // Don't do anything during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }

  user_role_grant_permissions('anonymous', ['view media']);
  user_role_grant_permissions('authenticated', ['view media']);
}
