<?php

/**
 * @file
 * Contains wxt_ext_breadcrumb.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wxt_ext_breadcrumb_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {

    case 'help.page.wxt_ext_breadcrumb':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Setting bread crumbs for all of WxT.') . '</p>';
      return $output;

    default:
  }
}
