name: build
on:
  push:
    branches:
      - 6.2.x

# Environment variables available to all jobs and steps in this workflow
env:
  COMPOSER_MEMORY_LIMIT: -1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        db:
         - type: mysql
           port: 3306
         - type: pgsql
           port: 5432

    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@master

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Setup dependencies
      run: |
        git clone --branch 11.2.x https://github.com/drupalwxt/site-wxt.git
        cd site-wxt
        rm composer.lock

    - name: Require patched wxt with Composer
      run: composer require drupalwxt/wxt:6.2.x-dev#${{ github.sha }} --working-dir=./site-wxt --ignore-platform-reqs

    - name: Build out the Drupal infrastructure
      run: |
        export DB_TYPE=${{ matrix.db.type }}
        export DB_PORT=${{ matrix.db.port }}
        cd site-wxt
        git clone --branch 11.2.x https://github.com/drupalwxt/docker-scaffold.git docker
        make build
        docker compose -f docker-compose.ci.yml up -d
        docker ps -a
        sleep 10

    - name: Run installation and tests
      run: |
        export DB_TYPE=${{ matrix.db.type }}
        export DB_PORT=${{ matrix.db.port }}
        cd site-wxt
        make drupal_install
        make drupal_migrate
        make test
